<a href="https://colab.research.google.com/github/saniaprl/H1D024011-PraktikumKB-Pertemuan8/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
dataset_path = "/content/drive/MyDrive/Colab Notebooks/H1D024011-PraktikumKB-Pertemuan8/rockpaperscissors"

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    dataset_path,
    target_size=(150, 150),
    batch_size=32,
    class_mode='categorical',
    subset='training',
)

validation_generator = train_datagen.flow_from_directory(
    dataset_path,
    target_size=(150, 150),
    batch_size=32,
    class_mode='categorical',
    subset='validation',
)

Found 794 images belonging to 3 classes.
Found 198 images belonging to 3 classes.


In [6]:
model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(150,150,3)),
    MaxPooling2D(2,2),
    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(512, activation='relu'),
    Dense(3, activation='softmax')
])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 148, 148, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 74, 74, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 72, 72, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 36, 36, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 34, 34, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 17, 17, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 36992)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 512)            │    18,940,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │         1,539 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,035,203 (72.61 MB)

 Trainable params: 19,035,203 (72.61 MB)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [8]:
history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=10
)

Epoch 1/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 229s 9s/step - accuracy: 0.7141 - loss: 0.7437 - val_accuracy: 0.8990 - val_loss: 0.3989
Epoch 2/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 56s 2s/step - accuracy: 0.8791 - loss: 0.2668 - val_accuracy: 0.9646 - val_loss: 0.1062
Epoch 3/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 58s 2s/step - accuracy: 0.9673 - loss: 0.0808 - val_accuracy: 0.9798 - val_loss: 0.0522
Epoch 4/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 55s 2s/step - accuracy: 0.9924 - loss: 0.0242 - val_accuracy: 0.9848 - val_loss: 0.0271
Epoch 5/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 55s 2s/step - accuracy: 0.9975 - loss: 0.0105 - val_accuracy: 0.9848 - val_loss: 0.0210
Epoch 6/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 82s 2s/step - accuracy: 0.9987 - loss: 0.0039 - val_accuracy: 0.9949 - val_loss: 0.0139
Epoch 7/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 54s 2s/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9899 - val_loss: 0.0221
Epoch 8/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 57s 2s/step - accuracy: 1.0000 - loss: 2.9290e-04 - val_accuracy: 0.9899 - val_

In [9]:
val_loss, val_acc = model.evaluate(validation_generator)
print(f'Validation loss: {val_loss}, Validation accuracy: {val_acc}')

7/7 ━━━━━━━━━━━━━━━━━━━━ 4s 457ms/step - accuracy: 0.9899 - loss: 0.0203
Validation loss: 0.020275015383958817, Validation accuracy: 0.9898989796638489


In [10]:
predictions = model.predict(validation_generator)
print(predictions)

7/7 ━━━━━━━━━━━━━━━━━━━━ 4s 509ms/step
[[8.18028893e-20 9.99999702e-01 2.58760593e-07]
 [4.94305050e-14 9.99999821e-01 7.99578288e-08]
 [7.77382238e-12 9.99994576e-01 5.35862910e-06]
 [1.05227039e-13 9.99999940e-01 5.49704104e-08]
 [1.22162534e-13 9.99999225e-01 6.84303018e-07]
 [2.76009955e-13 9.99999344e-01 6.52672043e-07]
 [4.77012432e-14 6.01552983e-06 9.99993980e-01]
 [8.19627704e-14 9.99999940e-01 4.99010895e-08]
 [1.08786957e-14 9.99999940e-01 2.18201812e-08]
 [5.79461022e-21 9.99999940e-01 4.38164858e-14]
 [5.17698109e-15 9.99999821e-01 8.09993139e-08]
 [1.33327160e-13 4.70947543e-06 9.99995172e-01]
 [7.01658715e-14 9.99999940e-01 1.49022537e-08]
 [4.03669792e-10 9.91649032e-01 8.35096370e-03]
 [7.90995233e-17 9.99999940e-01 5.05426864e-12]
 [1.94042793e-13 9.99998987e-01 9.52368168e-07]
 [5.30465992e-12 9.99965012e-01 3.49180336e-05]
 [1.28783941e-12 9.99998510e-01 1.40570410e-06]
 [5.95443291e-14 9.99999702e-01 2.94223980e-07]
 [1.06820364e-16 9.99999940e-01 7.34630179e-09]
 